# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dragon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Dragon")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #2B2D42;\n"
"}\n"
"\n"
"/*Buttons settings*/\n"
"QPushButton {\n"
"    color: #F9F5E3;\n"
"    border: #414464;\n"
"    border-radius: 5px;\n"
"    background-color: #414464;\n"
"    min-width: 137px;\n"
"    min-height: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D90429;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EF233C;\n"
"}\n"
"\n"
"/*Label settings*/\n"
"QLabel {\n"
"    color: #F9F5E3;\n"
"    border: 0px solid #414464;\n"
"    border-radius: 2px;\n"
"    padding: 2px #642669;\n"
"    background-color: #2B2D42;\n"
"    min-width: 137px;\n"
"    min-height: 19px;\n"
"}\n"
"\n"
"/*Line edit settings*/\n"
"QLineEdit {\n"
"    color: #F9F5E3;\n"
"    border: 2px solid #414464;\n"
"    border-radius: 2px;\n"
"    padding: 5px ;\n"
"    background-color: #2B2D42;\n"
"    min-width: 187px;\n"
"    min-height: 30px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Pages = QtWidgets.QTabWidget(self.centralwidget)
        self.Pages.setEnabled(True)
        self.Pages.setStyleSheet("/*TAB WIDGET*/\n"
"QTabWidget::pane {\n"
"    border: 2px solid #414464;\n"
"    border-bottom-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"QTabBar::tab {\n"
"    color: #F9F5E3;\n"
"    background-color: #414464;\n"
"    border: #642669;\n"
"    border-bottom-color: #2B2D42; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 10ex;\n"
"    padding: 2px;\n"
"}\n"
"QTabBar::tab:hover {\n"
"    background-color: #D90429;\n"
"}\n"
"QTabBar::tab:pressed {\n"
"    background-color: #EF233C;\n"
"}\n"
"\n"
"/*SCROLL BAR*/\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background-color: #2B2D42;\n"
"    width:14px;\n"
"    margin: 15px 0 15px 0;\n"
"    boder-radius: 0px;\n"
"}\n"
"QScrollBar:handle:vertical {\n"
"    background-color: #414464;\n"
"    min-height: 30px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar:handle:vertical:hover {\n"
"    background-color: #D90429;\n"
"}\n"
"QScrollBar:handle:vertical:pressed {\n"
"    background-color: #EF233C;\n"
"}\n"
"\n"
"/*Btn top*/\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: #414464;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: #D90429;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: #EF233C;\n"
"}\n"
"\n"
"/*Btn bottom*/\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #414464;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: #D90429;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: #EF233C;\n"
"}\n"
"\n"
"\n"
"/*Reset arrow*/\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background:none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background:none;\n"
"}\n"
"\n"
"/*Scroll Area settings*/\n"
"QScrollArea{\n"
"    border: none;\n"
"}\n"
"")
        self.Pages.setObjectName("Pages")
        self.Start = QtWidgets.QWidget()
        self.Start.setStyleSheet("")
        self.Start.setObjectName("Start")
        self.startLayout = QtWidgets.QGridLayout(self.Start)
        self.startLayout.setVerticalSpacing(4)
        self.startLayout.setObjectName("startLayout")
        self.Name = QtWidgets.QLabel(self.Start)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.startLayout.addWidget(self.Name, 0, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.Start)
        self.startButton.setStyleSheet("")
        self.startButton.setObjectName("startButton")
        self.startLayout.addWidget(self.startButton, 1, 0, 1, 1)
        self.Pages.addTab(self.Start, "")
        self.filestoOpen = QtWidgets.QWidget()
        self.filestoOpen.setMinimumSize(QtCore.QSize(0, 0))
        self.filestoOpen.setObjectName("filestoOpen")
        self.filesLayout = QtWidgets.QGridLayout(self.filestoOpen)
        self.filesLayout.setObjectName("filesLayout")
        self.scrollareaFiles = QtWidgets.QScrollArea(self.filestoOpen)
        self.scrollareaFiles.setStyleSheet("")
        self.scrollareaFiles.setWidgetResizable(True)
        self.scrollareaFiles.setObjectName("scrollareaFiles")
        self.scrollAreaWidgetContents_Files = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Files.setGeometry(QtCore.QRect(0, 0, 972, 922))
        self.scrollAreaWidgetContents_Files.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents_Files.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents_Files.setAutoFillBackground(False)
        self.scrollAreaWidgetContents_Files.setObjectName("scrollAreaWidgetContents_Files")
        self.filesAreaWidgetLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_Files)
        self.filesAreaWidgetLayout.setObjectName("filesAreaWidgetLayout")
        self.filePathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Files)
        self.filePathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filePathLabel.setObjectName("filePathLabel")
        self.filesAreaWidgetLayout.addWidget(self.filePathLabel, 0, 1, 1, 1)
        self.browseFileButtonLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Files)
        self.browseFileButtonLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.browseFileButtonLabel.setObjectName("browseFileButtonLabel")
        self.filesAreaWidgetLayout.addWidget(self.browseFileButtonLabel, 0, 2, 1, 1)
        self.addManyFilesButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_Files)
        self.addManyFilesButton.setObjectName("addManyFilesButton")
        self.filesAreaWidgetLayout.addWidget(self.addManyFilesButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.filesAreaWidgetLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.addFileButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_Files)
        self.addFileButton.setObjectName("addFileButton")
        self.filesAreaWidgetLayout.addWidget(self.addFileButton, 1, 0, 1, 1)
        self.fileNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Files)
        self.fileNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.filesAreaWidgetLayout.addWidget(self.fileNameLabel, 0, 0, 1, 1)
        self.removeFileButtonLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Files)
        self.removeFileButtonLabel.setObjectName("removeFileButtonLabel")
        self.filesAreaWidgetLayout.addWidget(self.removeFileButtonLabel, 0, 3, 1, 1)
        self.scrollareaFiles.setWidget(self.scrollAreaWidgetContents_Files)
        self.filesLayout.addWidget(self.scrollareaFiles, 0, 0, 1, 1)
        self.Pages.addTab(self.filestoOpen, "")
        self.folderstoOpen = QtWidgets.QWidget()
        self.folderstoOpen.setObjectName("folderstoOpen")
        self.foldersLayout = QtWidgets.QGridLayout(self.folderstoOpen)
        self.foldersLayout.setObjectName("foldersLayout")
        self.scrollareaFolders = QtWidgets.QScrollArea(self.folderstoOpen)
        self.scrollareaFolders.setWidgetResizable(True)
        self.scrollareaFolders.setObjectName("scrollareaFolders")
        self.scrollAreaWidgetContents_Folders = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Folders.setGeometry(QtCore.QRect(0, 0, 972, 922))
        self.scrollAreaWidgetContents_Folders.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents_Folders.setObjectName("scrollAreaWidgetContents_Folders")
        self.foldersAreaWidgetLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_Folders)
        self.foldersAreaWidgetLayout.setObjectName("foldersAreaWidgetLayout")
        self.addFolderButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_Folders)
        self.addFolderButton.setObjectName("addFolderButton")
        self.foldersAreaWidgetLayout.addWidget(self.addFolderButton, 1, 0, 1, 1)
        self.addManyFoldersButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_Folders)
        self.addManyFoldersButton.setObjectName("addManyFoldersButton")
        self.foldersAreaWidgetLayout.addWidget(self.addManyFoldersButton, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.foldersAreaWidgetLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.folderNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Folders)
        self.folderNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.folderNameLabel.setObjectName("folderNameLabel")
        self.foldersAreaWidgetLayout.addWidget(self.folderNameLabel, 0, 0, 1, 1)
        self.folderPathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Folders)
        self.folderPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.folderPathLabel.setObjectName("folderPathLabel")
        self.foldersAreaWidgetLayout.addWidget(self.folderPathLabel, 0, 1, 1, 1)
        self.removeFolderButtonLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Folders)
        self.removeFolderButtonLabel.setObjectName("removeFolderButtonLabel")
        self.foldersAreaWidgetLayout.addWidget(self.removeFolderButtonLabel, 0, 3, 1, 1)
        self.browseFolderButtonLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_Folders)
        self.browseFolderButtonLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.browseFolderButtonLabel.setObjectName("browseFolderButtonLabel")
        self.foldersAreaWidgetLayout.addWidget(self.browseFolderButtonLabel, 0, 2, 1, 1)
        self.scrollareaFolders.setWidget(self.scrollAreaWidgetContents_Folders)
        self.foldersLayout.addWidget(self.scrollareaFolders, 0, 0, 1, 1)
        self.Pages.addTab(self.folderstoOpen, "")
        self.gridLayout.addWidget(self.Pages, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name.setText(_translate("MainWindow", "Dragon"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.Pages.setTabText(self.Pages.indexOf(self.Start), _translate("MainWindow", "Start"))
        self.filePathLabel.setText(_translate("MainWindow", "File to open(Path)"))
        self.browseFileButtonLabel.setText(_translate("MainWindow", "Tap to browse path"))
        self.addManyFilesButton.setText(_translate("MainWindow", "Add many Files"))
        self.addFileButton.setText(_translate("MainWindow", "Add File"))
        self.fileNameLabel.setText(_translate("MainWindow", "Voice command(Name)"))
        self.removeFileButtonLabel.setText(_translate("MainWindow", "Tap to remove row"))
        self.Pages.setTabText(self.Pages.indexOf(self.filestoOpen), _translate("MainWindow", "Files to open"))
        self.addFolderButton.setText(_translate("MainWindow", "Add Folder"))
        self.addManyFoldersButton.setText(_translate("MainWindow", "Add many Folders"))
        self.folderNameLabel.setText(_translate("MainWindow", "Voice command(Name)"))
        self.folderPathLabel.setText(_translate("MainWindow", "Folder to open(Path)"))
        self.removeFolderButtonLabel.setText(_translate("MainWindow", "Tap tp remove row"))
        self.browseFolderButtonLabel.setText(_translate("MainWindow", "Tap to browse path"))
        self.Pages.setTabText(self.Pages.indexOf(self.folderstoOpen), _translate("MainWindow", "Folders to open"))
