centralwidget_StyleSheet = (
    "QWidget{\n"
    "    background-color: #2B2D42;\n"
    "}\n"
    "\n"
    "/*Buttons settings*/\n"
    "QPushButton {\n"
    "    color: #F9F5E3;\n"
    "    border: #414464;\n"
    "    border-radius: 5px;\n"
    "    background-color: #414464;\n"
    "    min-width: 137px;\n"
    "    min-height: 15px;\n"
    "}\n"
    "\n"
    "QPushButton:hover {\n"
    "    background-color: #D90429;\n"
    "}\n"
    "\n"
    "QPushButton:pressed {\n"
    "    background-color: #EF233C;\n"
    "}\n"
    "\n"
    "/*Label settings*/\n"
    "QLabel {\n"
    "    color: #F9F5E3;\n"
    "    border: 0px solid #414464;\n"
    "    border-radius: 2px;\n"
    "    padding: 2px #642669;\n"
    "    background-color: #2B2D42;\n"
    "    min-width: 137px;\n"
    "    min-height: 19px;\n"
    "}\n"
    "\n"
    "/*Line edit settings*/\n"
    "QLineEdit {\n"
    "    color: #F9F5E3;\n"
    "    border: 2px solid #414464;\n"
    "    border-radius: 2px;\n"
    "    padding: 5px ;\n"
    "    background-color: #2B2D42;\n"
    "    min-width: 187px;\n"
    "    min-height: 30px;\n"
    "}"
)

pages_StyleSheet = (
    "/*TAB WIDGET*/\n"
    "QTabWidget::pane {\n"
    "    border: 2px solid #414464;\n"
    "    border-bottom-radius: 3px;\n"
    "    border-top-right-radius: 3px;\n"
    "}\n"
    "QTabBar::tab {\n"
    "    color: #F9F5E3;\n"
    "    background-color: #414464;\n"
    "    border: #642669;\n"
    "    border-bottom-color: #2B2D42; /* same as the pane color */\n"
    "    border-top-left-radius: 4px;\n"
    "    border-top-right-radius: 4px;\n"
    "    min-width: 10ex;\n"
    "    padding: 2px;\n"
    "}\n"
    "QTabBar::tab:hover {\n"
    "    background-color: #D90429;\n"
    "}\n"
    "QTabBar::tab:pressed {\n"
    "    background-color: #EF233C;\n"
    "}\n"
    "\n"
    "/*SCROLL BAR*/\n"
    "QScrollBar:vertical {\n"
    "    border:none;\n"
    "    background-color: #2B2D42;\n"
    "    width:14px;\n"
    "    margin: 15px 0 15px 0;\n"
    "    boder-radius: 0px;\n"
    "}\n"
    "QScrollBar:handle:vertical {\n"
    "    background-color: #414464;\n"
    "    min-height: 30px;\n"
    "    border-radius: 7px\n"
    "}\n"
    "QScrollBar:handle:vertical:hover {\n"
    "    background-color: #D90429;\n"
    "}\n"
    "QScrollBar:handle:vertical:pressed {\n"
    "    background-color: #EF233C;\n"
    "}\n"
    "\n"
    "/*Btn top*/\n"
    "QScrollBar::sub-line:vertical {\n"
    "    border: none;\n"
    "    background-color: #414464;\n"
    "    height: 15px;\n"
    "    border-top-left-radius: 7px;\n"
    "    border-top-right-radius: 7px;\n"
    "    subcontrol-position: top;\n"
    "    subcontrol-origin: margin;\n"
    "}\n"
    "QScrollBar::sub-line:vertical:hover {\n"
    "    background-color: #D90429;\n"
    "}\n"
    "QScrollBar::sub-line:vertical:pressed {\n"
    "    background-color: #EF233C;\n"
    "}\n"
    "\n"
    "/*Btn bottom*/\n"
    "QScrollBar::add-line:vertical {\n"
    "    border: none;\n"
    "    background-color: #414464;\n"
    "    height: 15px;\n"
    "    border-bottom-left-radius: 7px;\n"
    "    border-bottom-right-radius: 7px;\n"
    "    subcontrol-position: bottom;\n"
    "    subcontrol-origin: margin;\n"
    "}\n"
    "QScrollBar::add-line:vertical:hover {\n"
    "    background-color: #D90429;\n"
    "}\n"
    "QScrollBar::add-line:vertical:pressed {\n"
    "    background-color: #EF233C;\n"
    "}\n"
    "\n"
    "\n"
    "/*Reset arrow*/\n"
    "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
    "    background:none;\n"
    "}\n"
    "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
    "    background:none;\n"
    "}\n"
    "\n"
    "/*Scroll Area settings*/\n"
    "QScrollArea{\n"
    "    border: none;\n"
    "}\n"
)
